
package localhost._8080;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceSOAPService", targetNamespace = "http://localhost:8080", wsdlLocation = "http://localhost:8080/WSSOAP/ServiceSOAPService?WSDL")
public class ServiceSOAPService
    extends Service
{

    private final static URL SERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESOAPSERVICE_EXCEPTION;
    private final static QName SERVICESOAPSERVICE_QNAME = new QName("http://localhost:8080", "ServiceSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSSOAP/ServiceSOAPService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESOAPSERVICE_WSDL_LOCATION = url;
        SERVICESOAPSERVICE_EXCEPTION = e;
    }

    public ServiceSOAPService() {
        super(__getWsdlLocation(), SERVICESOAPSERVICE_QNAME);
    }

    public ServiceSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESOAPSERVICE_QNAME, features);
    }

    public ServiceSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESOAPSERVICE_QNAME);
    }

    public ServiceSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESOAPSERVICE_QNAME, features);
    }

    public ServiceSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceSOAP
     */
    @WebEndpoint(name = "IServiceSOAPPort")
    public IServiceSOAP getIServiceSOAPPort() {
        return super.getPort(new QName("http://localhost:8080", "IServiceSOAPPort"), IServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceSOAP
     */
    @WebEndpoint(name = "IServiceSOAPPort")
    public IServiceSOAP getIServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080", "IServiceSOAPPort"), IServiceSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESOAPSERVICE_EXCEPTION!= null) {
            throw SERVICESOAPSERVICE_EXCEPTION;
        }
        return SERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
